version: "3.9"

services:
  firebird:
    image: jacobalberty/firebird:3.0
    container_name: firebird
    restart: unless-stopped
    ports:
      - "3050:3050"
    environment:
      ISC_PASSWORD: masterkey
      FIREBIRD_DATABASE: digifarma6.fdb   # só o nome
    volumes:
      - ./Firebird/data:/firebird/data    # certifique-se que ./Firebird/data/digifarma6.fdb existe
    healthcheck:
      test: ["CMD", "isql-fb", "localhost/3050:/firebird/data/digifarma6.fdb", "-user", "SYSDBA", "-password", "masterkey", "-q", "quit"]
      interval: 5s
      timeout: 5s
      retries: 30
