spring:
  config:
    activate:
      on-profile: legacy

  flyway:
    enabled: false

  datasource:
    firebird:
      jdbc-url: jdbc:firebirdsql://${FIREBIRD_HOST:redemaisfarma-firebird}:${FIREBIRD_PORT:3050}/${FIREBIRD_DB:digifarma6.fdb}?encoding=WIN1252&authPlugins=Legacy_Auth&wireCrypt=DISABLED
      username: ${FIREBIRD_USER:SYSDBA}
      password: ${FIREBIRD_PASSWORD:masterkey}
      driver-class-name: org.firebirdsql.jdbc.FBDriver
      hikari:
        maximum-pool-size: 5
        minimum-idle: 0
        idle-timeout: 60000
        connection-timeout: 10000
