-- V4__cliente_auditoria.sql
ALTER TABLE cliente
  ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_at DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN `version` BIGINT NOT NULL DEFAULT 0;
